name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: satishosk/taskmanager-backend
      FRONTEND_IMAGE: satishosk/taskmanager-frontend
      INFRA_REPO: https://github.com/OletiSatishKumar/Devops_Automation_Infra.git

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: vars
        run: echo "tag=${GITHUB_REF##*/}-$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:${{ steps.vars.outputs.tag }} ./backend
          docker push $BACKEND_IMAGE:${{ steps.vars.outputs.tag }}

      - name: Build & Push Frontend Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -t $FRONTEND_IMAGE:${{ steps.vars.outputs.tag }} ./client
          docker push $FRONTEND_IMAGE:${{ steps.vars.outputs.tag }}

      - name: Clone Infra Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://${{ secrets.GH_PAT }}@github.com/OletiSatishKumar/Devops_Automation_Infra.git infra-repo

      - name: Set Helm values file based on branch
        id: set-values
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "values_file=helm/taskmanager/values-prod.yaml" >> $GITHUB_OUTPUT
          else
            echo "values_file=helm/taskmanager/values-dev.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Update Helm Values
        run: |
          cd infra-repo
          sed -i "s|^\(\s*image:\s*\).*\$|\1$FRONTEND_IMAGE:${{ steps.vars.outputs.tag }}|" ${{ steps.set-values.outputs.values_file }}
          sed -i "/backend:/,/image:/ s|^\(\s*image:\s*\).*\$|\1$BACKEND_IMAGE:${{ steps.vars.outputs.tag }}|" ${{ steps.set-values.outputs.values_file }}

      - name: Commit & Push Changes to Infra Repo
        run: |
          cd infra-repo
          git add ${{ steps.set-values.outputs.values_file }}
          git commit -m "Update image tags to ${{ steps.vars.outputs.tag }} [CI]"
          git push origin main
